### ISSUE TITLE
Vue-приложение

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#1]
Развернуть Vue приложение.

Из основного: 
1. Vuex
2. Router
3. Sass (node-Sass)

**Comment by kirshin** [comment]
Готово d453621766ba5f1edb81f8f5f5fa880b67de3936

**Comment by IlyaDonskikh** [comment]
Отлично, закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
