### ISSUE TITLE
Листинг недвижимости

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#13]
Реализовать листинг недвижимости по макету https://zpl.io/a7Wzg7v.

Примечания:
1. Стоит обратить внимание, что на данный момент будет только одно или два предложения по недвижимости, так что есть возможность обойтись без страницы `show` и все отображать через `index`.
2. В блоке  `Offers` отображаются группы юнитов. Кнопка с ценой формируется исходя из предложений в этой группе юнитов и отображается для групп с общим количеством фракций > 0. Переход по кнопке ведет на страницу просмотра группы юнитов, макет и апи будут позже.
3. Максимальная ширина контента `840px`.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/16

**Comment by IlyaDonskikh** [comment]
Код ок. Закрывай.

**Comment by kirshin** [comment]
Фикс https://github.com/IlyaDonskikh/property_client/pull/16/commits/38bdcf970e0fbee9b29f7e7893ab6d71f222cf62

Ушло в `developer`
