### ISSUE TITLE
Страница группы юнитов

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#15]
Реализовать страницу группы юнитов по макеты: https://zpl.io/VQvLAOP. 

Примечания:
1. Несмотря на то, что в пагинации страница отмечена как юниты, технически это `UnitGroup`.
2. Реализовать соответсвующий код в АПИ, добавить задачу и дать на нее ссылку в комментариях.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/16

Задача для `api` https://github.com/IlyaDonskikh/property_api/issues/29

**Comment by IlyaDonskikh** [comment]
Один вопрос в коммите. Фикс и закрывай.

**Comment by kirshin** [comment]
Фикс https://github.com/IlyaDonskikh/property_client/pull/16/commits/38bdcf970e0fbee9b29f7e7893ab6d71f222cf62

Ушло в `developer`
