### ISSUE TITLE
Сделка

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#17]
Реализовать страницу сделки.

Макет с формой: https://zpl.io/V1OrJPw.
1. Для реализации формы рекомендуется использовать стандартные элементы UI-фреймворка, дизайн для этих элементов подгонять под макет не требуется.
2. На макете нарисованы блоки опций для
2.1. вторичной продажи с примечанием о базовой цене, автоматическим выбором и отображением только одной опции. 
2.2 первичной продажи с полным списком доступных опций.

---
Макеты на случай, если пользователь не авторизован или не пройдено `KYC`: https://zpl.io/a316WkW.

*KYC-уведомления:*
> Please note that in accordance with the website rules, all clients have to go through the following KYC procedure, thank you for your understanding.

> We have received your KYC application and will review it within 2-business days. Once confirmed you will receive an automatic email notification.`

> We are sorry, but something went wrong with your KYC Application. An email will be sent to you shortly with the additional information required, please complement and update your KYC application accordingly, using the edit button below.

**Comment by IlyaDonskikh** [comment]
Добавлен макет с формой.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/22

**Comment by IlyaDonskikh** [comment]
Мерж пока, но не закрывай.

После создания сделки нужно отправлять на ее странице: https://github.com/IlyaDonskikh/property_client/issues/18.

**Comment by kirshin** [comment]
Исправил в это реквесте https://github.com/IlyaDonskikh/property_client/pull/23

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай.
