### ISSUE TITLE
Панель сделок

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#18]
Реализовать `Dashboard` по макету: 
1. Листинг сделок - https://zpl.io/VQvpZpP
2. Страницу сделки - https://zpl.io/aMW8Ejr

**Comment by IlyaDonskikh** [comment]
Добавил макет списка сделок.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/23

**Comment by Khibar** [comment]
can you please invite me to the project

**Comment by IlyaDonskikh** [comment]
@Khibar what project?

**Comment by kirshin** [comment]
Ушло в `developer`

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай.
