### ISSUE TITLE
Панель KYC

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#19]
За основу навигации взять макет https://zpl.io/VQvpZpP.

На странице выводить `show` и кнопку создания или редактирования, если такие функции доступны.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/21

**Comment by IlyaDonskikh** [comment]
Выглядит отлично, проверю уже в работе завтра. Можно закрывать.

**Comment by kirshin** [comment]
Ушло в `developer`
