### ISSUE TITLE
Управление входящими первичными сделками 

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#20]
Реализовать интерфейс для подтверждения и отклонения сделок в панели `PropertyOwnerDashboard`.

В сабменю добавить `Deals`. Все сделки в этой панели `Incoming` (для юнитов без `bayer_id`, то есть на первичной продаже).

Листинг аналогичный листингу в `dashboard`. В `show`, кроме информации о юните и юнитгруппе, отображать данные `KYC` пользователя.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/23

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай. Будем смотреть уже по результату.

**Comment by kirshin** [comment]
Ушло в `developer`
