### ISSUE TITLE
Поведение интерфейса

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#26]
1. После создания Недвижимости и всех вложенных объектов сразу на `show`. Кроме того, загрузку и удаления картинок следует делать уже со страниц `show`.
2. Для главной страницы `PropertyOwnerPanel` добавить субнавигацию (аналогичную навигации `Dashboard`) с единственным, на данный момент пунктом `Property` и `Deals` для перехода к https://github.com/IlyaDonskikh/property_client/issues/20.
3. Кнопк Publish/Unpublish следует разместить в меню странице `show`.  
4. Переход на `show` в `PropertyOwnerPanel` требуется делать по клику на линию. 
5. В следствии выполнения пунктов 3-4 панель кнопку управления с выпадающим меню нужно убрать.
6. Формы должны сабмититься по клику на `Enter`.
7. Все активные ссылки/кнопки `cursor:pointer`. Обрати внимание на `breadcrumbs`.
8. Следует отображать количество фракции в `show` юнита в `PropertyOwnerPanel`.
9. После закрытия задачи https://github.com/IlyaDonskikh/property_client/issues/24 сделать так, чтобы пункт главного меню `PO-Dashboard (PropertyOwnerPanel)` отображался только для пользователей с доступом.
10. Почта на странице логина и регистрации должна быть автокомплитом.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/23

**Comment by IlyaDonskikh** [comment]
Ок. Мерж в девелопер.

**Comment by kirshin** [comment]
Ушло в `developer`

**Comment by IlyaDonskikh** [comment]
> Почта на странице логина и регистрации должна быть автокомплитом.

Не работает.

**Comment by kirshin** [comment]
Обновил информацию KYC 0ffd3263f8d2b9ccbcd5caf0d2e95f9dabb64eea 945b571bf29a14702e6942343ec1adcafa6b9ec4
Фикс редактирования юнита 6a41333c3e28b9c184c235c35b0be6e62956d865
Убрал глобальные уведомления об ошибках 911d3c44378ef50bb47d5acec8ae895bf18266b8
Добавил скроллинг после завершения переходов 96b5ff7e70aa4eb69c78b7793a82062c5ab261cd
Добавил текст для сабмита b72985c6ec61565ea51d2d8ef5c6692e492c4004
Фикс формы KYC f6d00477657680f6a69a21dd2aa5813d3c029ef7 f77fae9a19125d14144926282dd2ed777829747c
обновил загрузку файлов для Группы юнитов e7b3126c1d487f0cf56b14e5188d2c0038bbe6d1
Значения по умолчанию для Юнитов 952b5ec7a9ac78c4f380c73710bc08022ef4919b
Убрал валидацию на кол-во фракций 0034e205e8b956dbf16bddfd5c9dd6a5ee67ad74
Добавил прелодаер на алерт KYC 515dc3af4ea8b607210d136c88ec9eed2302c62c
Обновил страницу просмотра сделки в `Dashboard` c49b58f4512b36b7b96a4d51ef2418f805ca7a4d

**Comment by IlyaDonskikh** [comment]
Нумеруй, пожалуйста.

**Comment by IlyaDonskikh** [comment]
1. Все еще вижу кнопку подтверждения своего собственного оффера. 
2. Должна быть возможность отклонить собственный, еще не подтвержденный оффер. На данный момент кнопка не работает.
3. Данные `KYC` не отображаются.

**Comment by IlyaDonskikh** [comment]
1, 3. Фикс после обновления девелопера.
2. Ожидаю реализации.

**Comment by IlyaDonskikh** [comment]
`View Floorplan` на страницы группы юнитов - это ссылка для скачивания файла. Не нужно дополнительного интерфейса для просмотра.

**Comment by kirshin** [comment]
Фикс 19f174a0c0ad723c0a98d71726e0110af04e5653

**Comment by IlyaDonskikh** [comment]
Ок. Мелкие замечание в коммите. Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
