### ISSUE TITLE
Управление пользователями

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#29]
Добавить:
1. `AdminPanel` и управления пользователями `index + show + update`.
2. Сабменю: `KYC` и `Users`.
3. Пункт в главное меню `Admin Panel`, только для пользователей с ролью `administrator`. Переброска на KYC:  https://github.com/IlyaDonskikh/property_client/issues/28

Главное меню следует обновить после того, как Кибар закончит https://github.com/IlyaDonskikh/property_client/issues/24.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/23

**Comment by IlyaDonskikh** [comment]
Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
