### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#31]
Replace `Register` and `Get Started` links  with a link leading to the property page and with text "Explore" or something like that  if user signed in.

**Comment by IlyaDonskikh** [comment]
I recommend to complete the work in the `feature/landing` branch. But don't forget to pull last version from developer.

Or you can switch to `git checkout feature/landing` and `merge developer` if you already using last version of `developer` branch.

**Comment by Khibar** [comment]
Hey bro, I changed two fo the CTA to Explore and pushed to properties page, bottom CTA is linked to registration so I kept that, I also fixed the navbar and the icon/name bug and the main banner content aligned on left.

uploaded to new branch feature/landing-navbar: a82735cccf45e904fc42d466bcc41fc43249199a

**Comment by IlyaDonskikh** [comment]
Sorry, i published not full version of issue. We need to change link only if user signed in.

Update pls.

**Comment by Khibar** [comment]
updated conditional replacing button & link based on user authentication

**Comment by IlyaDonskikh** [comment]
Thanks and create pull request pls. I will merge and fix rest of code by myself.

**Comment by Khibar** [comment]
done: https://github.com/IlyaDonskikh/property_client/pull/35
