### ISSUE TITLE
Список активов

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#33]
Добавить в сабменю `Dashboard` пункт `Property` и страницу `dashboard/units/Index.vue`. 

На этой должны отображаться все юниты с `fractions > 0`, который на данный момент находятся на балансе пользователя, даже те, что выставлены на продажу. Кроме того, в теле юнита следует передавать данные `unit_group`, чтобы можно было отображать полезные данные в интерфейсе.

Нюанс в том, что по каждому юниту нужно выводить прибыль, которую человек получит по условиям опции контракта. Однако фракции одного юнита может быть куплены в разное время и с разными опциями, кроме того, юниты выставленные на продажу тоже должны отображать предполагаемый доход до того момента, пока продажа не совершена.

**Comment by kirshin** [comment]
Страницы списка и карточки юнита https://github.com/IlyaDonskikh/property_client/pull/34 и много всяких фиксов

Ушло в `developer`

**Comment by IlyaDonskikh** [comment]
> Нюанс в том, что по каждому юниту нужно выводить прибыль, которую человек получит по условиям опции контракта. Однако фракции одного юнита может быть куплены в разное время и с разными опциями, кроме того, юниты выставленные на продажу тоже должны отображать предполагаемый доход до того момента, пока продажа не совершена.

Вот это уточни как реализовано.

**Comment by kirshin** [comment]
Доработал 046b25bd457e55d3126ca9d151284d76ab587097

**Comment by IlyaDonskikh** [comment]
Вопрос в коммите.

**Comment by kirshin** [comment]
Расчет ожидаемого дохода в `API`  https://github.com/IlyaDonskikh/property_api/commit/b72b6b76e4dccfffd685b6167a3f78bbc92c5b8b

**Comment by IlyaDonskikh** [comment]
Посмотрел. 

Вопрос в том, каким образом рассчитывается - когда выплачивать доход.  

Так как доход рассчитывается с момента покупки, а не с момента заключения `primary_deal`, то когда покупатель разбивает юнит для продажи, то твой случай этого не учитывает.

Рассчитываемый доход должен выдавать хэш `{ date, value, currency }` в рамках каждой сделки по каждому из юнитов, даже если они разбиты на покупку и продажу.

**Comment by kirshin** [comment]
Обновил https://github.com/IlyaDonskikh/property_api/commit/350af5cb6d95997fde954b54ffa792aab5badb76
https://github.com/IlyaDonskikh/property_client/pull/63

**Comment by IlyaDonskikh** [comment]
Замечание в коммите.

**Comment by IlyaDonskikh** [comment]
По клиенту нет вопросов, в апи есть замечание.

**Comment by kirshin** [comment]
Доработка `api`, добавлена дата покупки https://github.com/IlyaDonskikh/property_api/commit/2c23103775103ee461d4379586345427ce3c216d

**Comment by IlyaDonskikh** [comment]
Отлично. Оставил комментарий в коммите. Обнови и закрывай.

**Comment by kirshin** [comment]
Обновил

https://github.com/IlyaDonskikh/property_api/commit/bbf69d560920a7c0b994e463374bdba75ae464de
