### ISSUE TITLE
Вторичная продажа

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#36]
На странице юнита в дашборде реализовать кнопку для публикации на вторичную продажу. На странице вторичной продажи владелец может отменить ее.

**Comment by kirshin** [comment]
Готово 4cc49af48f676e2ac0016c0e09ae5639d62f9143 b134829b4161bf5a5113be24b1aaadbfead08af7

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
