### ISSUE TITLE
Максимальное количество фракций

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#37]
На данный момент форма сделки с количеством фракций больше чем `fractions_max_per_unit_bayer ` сабмитится и редиректит на новую страницу. Однако, сделка при этой не создается.

При сабмите такой формы должна отображаться ошибка.

Отдельно обрати внимание, что пользователь не может быть обладателем большего количества фракций на юнит, чем `fractions_max_per_unit_bayer ` даже при условии, что он покупает эти фракции в разных сделках.

**Comment by kirshin** [comment]
Фикс  https://github.com/IlyaDonskikh/property_client/commit/0034e205e8b956dbf16bddfd5c9dd6a5ee67ad74

Будет показана ошибка которую вернет `api`

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
