### ISSUE TITLE
Фавикон

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#38]
Добавить факвикон через: 
![favicon](https://user-images.githubusercontent.com/3100222/58769088-1124bc00-85ac-11e9-8114-19615f24ff3d.png)

**Comment by kirshin** [comment]
Готово d431a1ad3ef843a4abfe1ffa366483116a932f7b

**Comment by IlyaDonskikh** [comment]
Таким способом фавикон сжимается в `base64`. Нужно, чтобы был оригинальный файл.

**Comment by kirshin** [comment]
Фикс e48acf4fad31087a1fa6aa4472b5b4bbfcd57b2d и добавил оптимизацию файлов `css` для `prod`

**Comment by IlyaDonskikh** [comment]
А по какой причине файлы стакаются в изображениях? Может есть какой-то способ избежать этого?

И, кажется, раньше в папке были только используемые приложением изображения. А теперь все подряд.

Может быть есть возможность классической реализации?

1. https://vuejs-templates.github.io/webpack/static.html (Раздел: "Real" Static Assets).
2. https://vuejs-templates.github.io/webpack/structure.html

**Comment by kirshin** [comment]
Готово e075f7dda44af17b041d7608b8f73932d701d258

**Comment by IlyaDonskikh** [comment]
Выглядит отлично. Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
