### ISSUE TITLE
Navigation Dropdown menu

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#39]
Navigation dropdown menu and sign up menu should close in user click outside the dropdown block.

**Comment by IlyaDonskikh** [comment]
I installed https://github.com/Akryum/v-tooltip plugin and would be good if you will use it.

**Comment by Khibar** [comment]
Not quite sure what to use it for,

**Comment by IlyaDonskikh** [comment]
I thought you are done. Where is a reference to the fix?

**Comment by Khibar** [comment]
sorry had added the reference in the wrong place (in the pull request) here it is: 2c369bdff3d68ac92a2212b1bd50eb6c165da4d3

**Comment by Khibar** [comment]
Link to pull request for outside element click to close signout and navbar: https://github.com/IlyaDonskikh/property_client/pull/52

**Comment by IlyaDonskikh** [comment]
Great! Thanks!
