### ISSUE TITLE
Управление вторичными юнитами

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#40]
Не отображать и запретить редактировать вторичные юниты в `property_owner_panel -> unit_group`.

Сейчас там отображаются и те юниты, которые размещены владельцем недвижимости, и те, что есть у покупателей, включая те, что выставлены на вторичную продажу.

<img width="928" alt="Screenshot 2019-06-04 at 01 01 03" src="https://user-images.githubusercontent.com/3100222/58837437-3ffe6900-8664-11e9-8577-090799d0edfb.png">

**Comment by kirshin** [comment]
Сделал фикс в `API`https://github.com/IlyaDonskikh/property_api/commit/3116afcdd64db913ff8d1f1e5197867ff4bb5136

**Comment by IlyaDonskikh** [comment]
Отлично, закрывай.
