### ISSUE TITLE
KYC вторичной сделки

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#42]
У вторичной сделки должно отображаться KYC того, кто эту сделку предлагает, а не продавца.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/46

Для сделок на покупку показываю продавца
Для сделок на продажу показываю покупателя

**Comment by IlyaDonskikh** [comment]
Продавцу нужно верфицировать покупателя. Нет смысла показывать продавцу - информацию о нем самом. 

Может я не понял, мысль, которую ты хотел донести, но то что ты написал выглядит не совсем разумным: 

> Для сделок на покупку показываю продавца
> Для сделок на продажу показываю покупателя

Не существует сделок только на продажу и только на покупку. Каждая сделка имеет покупателя и продавца. При этом покупатель не должен видеть KYC-продавца. А продавцу не зачем смотреть на свое `KYC`, его интересуют данные покупателя.

**Comment by kirshin** [comment]
Я имел ввиду, что на странице сделки из  секции `Dashboard/Deals/Buy` показываю `KYC` того кто продает недвижимость, для сделки из секции `Dashboard/Deals/Sell` показываю `KYC` желающего приобрести недвижимость

**Comment by IlyaDonskikh** [comment]
KYC владельца недвижимости не нужно показывать.

Тому кто продает должно всегда отображаться `KYС` того, кто покупает.  Покупателю не нужно отображаться `KYC` продавца.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/46

**Comment by IlyaDonskikh** [comment]
Оставил комментарий. На всякий случай, обрати внимание, что KYC должно отображаться только продавцу. В случае первичной продажи это `property_owner`, вторичной - `buyer_id`.

**Comment by kirshin** [comment]
Ушло в `developer`
