### ISSUE TITLE
Информация формы сделки

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#44]
При оформлении сделки данные обновляются после ввода количества фракции и любого экшена. А должны обновляться при изменении значения поля.

При этой не нужно тригерить систему, каждый раз, когда значение меняется. То есть, когда вводится 12, то должен быть один запрос на 12, а не два `1`, `12`.

Для этого пишется скрипт, который после ввода значения добавляет его в переменную `value = field.value` и делает задержку в 1 секунду (например). После этой задержки проверяет значение поля `value == field.value`. Если значения ровны, то выполняется запрос, если нет, то новое значение `value = field.value`, выполняется задержка и очередная проверка.

**Comment by kirshin** [comment]
Обновил 27d7a53312998f7bc5e24cb30eae548928763bea, заменил поле ввода которое поддерживает реактивность изменений

**Comment by IlyaDonskikh** [comment]
Отлично, закрывай.
