### ISSUE TITLE
KYC в админ-панеле

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#45]
После подтверждения/отклонения KYC в админпанели страница остается без изменений с бейджем pending. 

Должна обновляться.

**Comment by kirshin** [comment]
На локальной копии не смог воспроизвести проблему

**Comment by IlyaDonskikh** [comment]
Уточню, что модель обновляется, а страница нет. После перезагрузки страницы данные отображаются корректно.

Если не удается воспроизвести, то закрывай.

**Comment by kirshin** [comment]
Я думаю что происходит ошибка на стороне `api`, по этой причине не обновляется форма

На клиенте добавил обработчик ошибок https://github.com/IlyaDonskikh/property_client/pull/51
На `api` обработку всех ошибок https://github.com/IlyaDonskikh/property_api/commit/1a410dcb8917d2a67b7696a42f037dee271e0961

**Comment by IlyaDonskikh** [comment]
Ок. Будем тестировать. Однако, не понятно о какой форме ты говоришь.

В апи оставил небольшое замечание. Задачу можно закрывать.

**Comment by kirshin** [comment]
Ушло в `developer`
