### ISSUE TITLE
Размер файлов

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#47]
Если пользователь загружает изображение, например в KYC, размером 15+ мегабайт, то форма сабмитися, но данные не сохраняются.

Возможно, стоит сделать какой-то превалидатор на размер изображения перед отправкой.

**Comment by kirshin** [comment]
Добавил обработку ответа `API` https://github.com/IlyaDonskikh/property_client/pull/51

Пример http://joxi.ru/KAxo4d1TZ811K2

**Comment by IlyaDonskikh** [comment]
Отлично! Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
