### ISSUE TITLE
Эффект перезагружаемой страницы

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#48]
При переходе на страницу недвижимости https://s3.ap-southeast-1.amazonaws.com/property-client-staging/index.html#/properties и страницу группы юнитов происходит визуальный (не технический) эффект перезагрузки страницы (на короткое время все содержимое `body` становится белым). При этом, при переходе на страницу создания сделки эффекта уже не наблюдается.

Разберись в причине, пожалуйста.

**Comment by kirshin** [comment]
Фикс https://github.com/IlyaDonskikh/property_client/pull/50

**Comment by IlyaDonskikh** [comment]
На сделке, кстати, не было этого эффекта. А лоудер был классный, может можно его как-то адаптировать внутрь контейнера, а не на весь экран?

**Comment by kirshin** [comment]
Адаптировал 3f20d1f9d996f325b4c59078998dc4159b8d8692

**Comment by kirshin** [comment]
Ушло в `developer`

**Comment by IlyaDonskikh** [comment]
Отлично. Закрывай.
