### ISSUE TITLE
Двухфакторная аутентификация

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#49]
1. Заменить раздел `KYC` на `Profile` в `Dashboard`.
2. Добавить на страницу блок для двухфакторной аутентификации.

Контент блока:
Заголовок: 2-factor Authentication
Таблица: Status | enabled/disabled
Кнопка: Setup/Disable.

По клику на Setup переход в настройку аутентификации (аналогично с DeeMoney).

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/55

**Comment by IlyaDonskikh** [comment]
Ок. Мерж, буду тестить на клиенте.

**Comment by kirshin** [comment]
Ушло в `developer`

**Comment by IlyaDonskikh** [comment]
Лишние пробелы между словами:
<img width="356" alt="Screenshot 2019-06-08 at 12 43 56" src="https://user-images.githubusercontent.com/3100222/59145345-273ade00-89eb-11e9-9ff5-b0e8fd7f351e.png">

Кроме того, если режим `!Rails.env.production?`, то добавляй в название для Аутентификатора `Property_#{Rails.env}`.

**Comment by kirshin** [comment]
Доработал 
https://github.com/IlyaDonskikh/property_client/pull/66
https://github.com/IlyaDonskikh/property_api/pull/51

**Comment by IlyaDonskikh** [comment]
Не уверен, что размещение двухфакторной аутентификации внутри компонента `SignIn`, а не через `pages` выгодное решение. Так как в целом, не для всех страниц нужна двухфакторка и постепенно мы будем выводить страницы с низким уровнем доступа из под этого фильтра.

Не понятно, где сама проверка в `API` при логине. `otp_required: true` - автоматически решает этот вопрос? Рекомендую создать задачу, где продолжим обсуждение `API`.

**Comment by kirshin** [comment]
> Не уверен, что размещение двухфакторной аутентификации внутри компонента SignIn

Пока не было задач для где нужно требовать отдельно подтверждение двух факторной авторизации, по этому требую ввода кода сразу и считаю пользователя не авторизованным пока не введен код (Если у пользователя активирована двухфакторная авторизация)  

> Не понятно, где сама проверка в API при логине
 -  Первым запросом проверяем логин
 -  Если у пользователя активирована двух факторная авторизация, требую ввести код и делаю второй запрос

**Comment by kirshin** [comment]
Ушло в `developer`
