### ISSUE TITLE
Панель управления недвижимостью

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#5]
Реализовать интерфейс `PropertyOwnerPanel` для
1. Недвижимости
2. Группы Юнитов
3. Юнитов

**Comment by kirshin** [comment]
Готово 
https://github.com/IlyaDonskikh/property_client/pull/9
https://github.com/IlyaDonskikh/property_client/pull/10

**Comment by kirshin** [comment]
Обновить формы управления недвижимостью в связи с изменениями набора полей и добавить управление Опциями контракта

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/10

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай. Будем подгонять данные и работу с ними под макеты по мере поступления.

**Comment by kirshin** [comment]
Ушло в `developer`
