### ISSUE TITLE
Фильтр сделок

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#53]
Требуется добавить чебокс `Only Pending Confirmation` на страницы отображающие сделки и фильтровать записи в соответсвии с этим чекбоксом.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/58

**Comment by kirshin** [comment]
Ушло в `developer`

**Comment by IlyaDonskikh** [comment]
Не гибко и в целом больше похоже на костыль. Это должно проходить через запрос к `API`.

**Comment by kirshin** [comment]
Обновил

https://github.com/IlyaDonskikh/property_client/pull/64
https://github.com/IlyaDonskikh/property_api/commit/155328b72790d36abf2f7f83fd3e8c39e366d015

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
