### ISSUE TITLE
Валюты прайсов

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#54]
1. В PropertyOwnerPanel на странице `UnitGroup` добавить Add Default Price, а на страницу `Unit` `Add Price`. 
2. Цены на сайте отображаются в долларах по умолчанию, если нет цены в долларах, то в любой другой.
3. При выборе опции на странице создания сделки цены отображаются в валюте опции. Если к юниту привязана сделка, то цена юнита отображается в той валюте, с какой опций оформлена сделка.

Остальное в соответствии с задачей: https://github.com/IlyaDonskikh/property_api/issues/46.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/71

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай. Буду смотреть уже на клиенте.

**Comment by kirshin** [comment]
Ушло в `developer`
