### ISSUE TITLE
Фильтр юнитов

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#57]
На страницу `UnitGroup#show` добавить фильтр по типу сделки `Primary ($unit_amount)` и `Secondary ($unit_amount)` над списком юнитов.

По умолчанию выбран `Primary`.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/59

**Comment by kirshin** [comment]
Ушло в `developer`

**Comment by IlyaDonskikh** [comment]
Это должны быть запросы к `API`.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_api/pull/50

**Comment by IlyaDonskikh** [comment]
По клиенту нет претензий, по апи есть вопросы. Рекомендую открыть задачу для апи и продолжить обсуждение там.

**Comment by kirshin** [comment]
Задача для `API` 

https://github.com/IlyaDonskikh/property_api/issues/52

Ушло в `developer`
