### ISSUE TITLE
String Updates New Deal Page

### ISSUE THREAD

**Issue by Khibar** [IlyaDonskikh/property_client#67]
1.  Please add a paragraph under the Payment Currency title with the following string:
New String: "4% interest to be paid in the payment currency"

2. Please Change Radio Button String:

Old String: 4% SGD per year --> New String: SGD
Old String: 4% USD per year --> New String: USD

**Comment by IlyaDonskikh** [comment]
Divided into tasks: https://github.com/IlyaDonskikh/property_api/issues/53, https://github.com/IlyaDonskikh/property_client/issues/68.
