### ISSUE TITLE
Выбор валюты сделки

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#68]
В продолжение: https://github.com/IlyaDonskikh/property_api/issues/53.

1. Заменить в форме вывод опции на выбор валюты.
2. Автоматически выбирать первую валюту в списке.
3. Под `label` выводить текст опции, связанный с валютой.  
4. Отображать цену, связанную с валютой.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/71, делал все в одном реквесте

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай и мерж в девелопер. Буду смотреть уже в интерфейсе.

**Comment by IlyaDonskikh** [comment]
Перенеси, пожалуйста, текст опции под `Payment Currency`. И после этого можно закрывать.

Отличная работа!

**Comment by kirshin** [comment]
Фикс 0d149abbc9c166c398c00f55ad0741cb5ef75f57

Ушло в `developer`
