### ISSUE TITLE
Прогресс бар

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#7]
Добавить прогрессбар при переходе между страницами через навигационное меню.

Предлагаемый плагин: https://github.com/hilongjw/vue-progressbar и демо http://hilongjw.github.io/vue-progressbar/index.html.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/12

**Comment by IlyaDonskikh** [comment]
Отлично, закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
