### ISSUE TITLE
Пользовательское KYC

### ISSUE THREAD

**Issue by IlyaDonskikh** [IlyaDonskikh/property_client#8]
Реализовать возможность создания, просмотра и редактирования KYC по правилам, аналогичным Димани.

**Comment by kirshin** [comment]
Готово https://github.com/IlyaDonskikh/property_client/pull/11

**Comment by IlyaDonskikh** [comment]
Ок. Закрывай.

**Comment by kirshin** [comment]
Ушло в `developer`
